### ISSUE TITLE
The right way to use meteor-semantic-ui's modal?

### ISSUE THREAD

**Issue by wuxianliang** [nooitaf/meteor-semantic-ui#25]
When I use modal, I found if I open it with meteor template, I mean, rendering when a session variable is true, there is event binding but transition animation, else if I open modal with jquery $('.ui.modal').modal('show'),  there is transition animation but event bindings. So I think there is other ways to use modal which keep functions from Blaze and animations from Semantic-ui at the same time. Dynamic part for integration of these two frameworks is not so straightforward. Would you like to point out the right way to use meteor-semantic-ui's modal? Thank you very much.

**Comment by tehfailsafe** [comment]
In the example above, how do I access the context of the template? Say I want to save some data from the modal and I require the _id of the template context and there are multiple form elements. Is it really best to set 5 session variables? And then where to I place the actual meteor call method (or with insecure simply add the insert function)?

**Comment by nooitaf** [comment]
Instead of Sessions you could use it like this too...

`````html
<head>
  <title>semantic-modal-example</title>
</head>

<body>
  {{> carsView}}
</body>

<template name="carsView">
	{{#each cars}}
		{{> carButton}}
	{{/each}}
</template>


<template name="carButton">

	<button class="openModal">{{name}}</button>

  <div class="ui modal">
    <div class="content">
      <div class="ui fluid input">
        <input class="carname{{_id}}" placeholder="car name here" type="text" value="{{name}}">
      </div>
    </div>
    <div class="actions">
      <div class="ui button cancel">Cancel</div>
      <div class="ui button ok">OK</div>
    </div>
  </div>

</template>
`````
`````javascript
Cars = new Mongo.Collection('cars');

if (Meteor.isClient) {

  Template.carsView.helpers({
    cars: function () {
      return Cars.find();
    }
  });

  Template.carButton.events({
    'click .openModal': function (event,template) {
      var self = this;
      template.$('.modal')
        .modal({
          onDeny    : function(){
            console.log('canceled')
            return false;
          },
          onApprove : function() {
            var name = $('.carname'+self._id).val();
            console.log(self._id,name);
            Cars.update({_id:self._id},{$set:{name:name}});
          }
        })
        .modal('show')
      ;
    }
  });

}


if (Meteor.isServer){
  Meteor.startup(function(){
    if (!Cars.findOne()){
      Cars.insert({'name':'dodge'});
      Cars.insert({'name':'fiat'});
      Cars.insert({'name':'mercedes'});
    }
  })
}
`````

**Comment by tehfailsafe** [comment]
Ah, var self = this. Totally forgot about that fundamental trick. I worked around it with global variables but that is much nicer, thanks!

**Comment by ghost** [comment]
I just found out that Blaze events doesn't work for Semantic UI modal templates.
A workaround is to put the modal content in a separate template.
For the modal buttons the onApprove and onDeny callback can be used.

**Comment by joryphillips** [comment]
@Sanjo Can you elaborate a little more on how to structure the workaround? Thanks!

**Comment by ghost** [comment]
@joryphillips Here is an example of a modal with form, based on my use case.

Node: I use the template extensions package for the hooks instead of onCreated, onRendered (https://github.com/aldeed/meteor-template-extension). This is not necessary.

### The modal template

``` html
<template name="modal">
  <div class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
      {{header}}
    </div>
    <div class="content">
      {{> modalForm}}
    </div>
    <div class="actions">
      <div class="ui deny button">Cancel</div>
      <div class="ui {{#unless isFilledOut}}disabled{{/unless}} primary approve button">
        {{approveText}}
      </div>
    </div>
  </div>
</template>
```

``` js
var template = Template.modal;

template.hooks({
  created: function () {
    var self = this;

    _.defaults(self.data, {
      header: 'My modal header',
      approveText: 'Submit'
    });

    self.form = new ReactiveVar(null);

    self.getForm = function () {
      return self.form.get();
    };
  },

  rendered: function () {
    var self = this;

    self.form.set(
      Blaze.getView($('form', self.firstNode).get(0)).templateInstance()
    );

    var modal = self.$('.ui.modal');
    modal.modal({
      onApprove: function () {
        self.getForm().submit();
      },
      onHidden: function () {
        Blaze.remove(self.view);
      }
    });
    modal.modal('show');
  }
});

template.helpers({
  isFilledOut() {
    var self = Template.instance();
    var formInstance = self.getForm();

    return formInstance && _.every(formInstance.form, function (field) {
      return !!field.get();
    });
  }
});
```

### The modal content template (in this case the form)

``` html
<template name="modalForm">
  <form class="ui form">
    {{!-- TODO: Add form inputs --}}
  </form>
</template>
```

``` js
var template = Template.modalForm;

template.hooks({
  created: function () {
    var self = this;

    self.form = {
      // myInput: new ReactiveVar(null)
    };

    self.submit = function () {
      // TODO: Implement form submit action
    };
  }
});
```

### Service to show modals

``` js
Modal = {
  show: function (templateName, data = {}) {
    var template = Template[templateName];
    var parentNode = document.body;

    Blaze.renderWithData(template, data, parentNode);
  }
};
```

**Comment by joryphillips** [comment]
@Sanjo thank you very much for the quick response! Just wondering, what event fires the modal in your use case?

**Comment by ghost** [comment]
This callback is called by semantic ui when the user clicks the approve button.

``` js
onApprove: function () {
  self.getForm().submit();
},
```

`self.getForm().submit()` is the submit method that I have defined in the modalForm template.

**Comment by nooitaf** [comment]
Just reminding you guys of the new location of this package ;)
- css (like this one here but up to date): https://atmospherejs.com/semantic/ui-css
- less version + themes: https://atmospherejs.com/semantic/ui

**Comment by dalgard** [comment]
I've found a pretty clean solution for using Semantic UI's modals; you can see the code here:
[Blaze modals: Semantic UI](http://meteorpad.com/pad/TFQYcaab8JnocCpoY/Blaze%20modals:%20Semantic%20UI)

A lengthier explanation of the pattern can be found here:
[A pattern for incorporating modals (Semantic UI)](https://meteor.hackpad.com/A-pattern-for-incorporating-modals-wo8Uhynt02r)

(Incidentally, applying the pattern to Foundation modals is even simpler:
[Blaze modals: Foundation](http://meteorpad.com/pad/eCY5QrpBJThaKDaTj/Blaze%20modals:%20Foundation))

**Comment by joryphillips** [comment]
@dalgard That hackpad was very well written and taught me everything I needed to know. Thanks!!

**Comment by dalgard** [comment]
I'm glad :)

**Comment by seddonm1** [comment]
@dalgard 
Thanks for your code it is very helpful.

I have a couple of questions that I believe you will be able to answer:
- Do you know how to reproduce the 'closable' behaviour of the modal (allow you to close the modal by clicking on the dimmer) with your pattern? Could we attach another event handler to simulate this behaviour?
- Do you know how to pass variables to the modal target (appMyActionModel) so that an _id value could be passed and handled in the template's methods. Currently I am using session variables but it feels like a hack.

Thanks

**Comment by dalgard** [comment]
Both your requests are met by the pattern I've outlined. In fact, I consider them central to the pattern.

**Comment by seddonm1** [comment]
@dalgard 
Thanks. I have just read the documentation on the Blaze.renderWithData method and now understand much better what it is doing and successfully passing data.

**Comment by dalgard** [comment]
These days, I'm using a custom [openModal](https://gist.github.com/dalgard/cf0a8c6c0d4db4e8ad87) binding with the `dalgard:viewmodel` package, by the way.

**Comment by minafarid** [comment]
@Sanjo Great tip! I have been banging my head in the wall for 30 minutes!

**Comment by zayau** [comment]
I had problem too. When you have modal template and {{> modalTemplate}} in a parent template and do .modal('show') on onRendered of the parent template. Other jquery initializations on the modal template's onRendered doesn't run second time when you open the modal even in tracker.autorun environment. If someone has a solution to this problem, can share please? thanks.

**Comment by Gatux** [comment]
If you want to use Meteor events with semantic ui modal, try to initiate the modal with "detachable: false". It works for me :)

**Comment by talha-asad** [comment]
Yeah but kinda kills all the good stuff :)

This post thread has been really helpful. Thanks alot.

**Comment by rijk** [comment]
@Sanjo Dude thank you for that great tip of putting the modal content in a separate template!

@nooitaf maybe we want to put this in the package's readme? https://github.com/nooitaf/meteor-semantic-ui/issues/25#issuecomment-116277532 
Think it will be helpful to others.

**Comment by arist0tl3** [comment]
@dalgard Just wanted to say thanks for that hackpad -- especially the onHidden callback method of blaze removal!

**Comment by gVolop** [comment]
if you wanna to use with meteor-blaze template events inside semantic model, you can separate all modal content to another template, and it worked perfectly.
only modal himself events didn't work.

# _this didn't work_

**HTML**

```html
<template name="firstModal">
    <div id="firstModal" class="ui wide modal">
        <i class="close icon"></i>
        <input type="button" class="ui button" value="click me">
    </div>
</template>
```

**JS**

```js
Template.firstModal.events({
    'click .button': function(event, template){
        alert('click !!!!!!!')
    }
});
```

# _but this is perfect!!_

**HTML**

```html
<template name="firstModal">
    <div id="firstModal" class="ui wide modal">
        <i class="close icon"></i>
        {{>firstModalContent}}
    </div>
</template>

<template name="firstModalContent">
    <input type="button" class="ui button" value="click me">
</template>
```

**JS**

```js
Template.firstModalContent.events({
    'click .button': function(event, template){
        alert('click !!!!!!!')
    }
});
```

**Comment by frankapimenta** [comment]
just by change I have a modal in a page and sometimes it works fine...
but there are times that I have this error:

```javascript
Uncaught TypeError: $(...).modal is not a function
```
any of you have any idea regarding this?

somehow there are problems in loading jquery and semantic ui but this is the only place where I have problems with semantic ui related features.

**Comment by lesliedoghouse** [comment]
@dalgard 
Hi, I really need a good and clean solution for using Semantic UI Modal with proper event capture.

I read that your solution is very good but too bad both of your link (sample and explanation) are broken now. Do you still have the solution and explanation? Thanks.

Regards,
Lesz
