### ISSUE TITLE
Moving to Official Semantic-org

### ISSUE THREAD

**Issue by nooitaf** [nooitaf/meteor-semantic-ui#28]
Just a heads up...

14 month ago i thought, "Why is there no semantic-ui package for meteor?", at the time it was semantic-ui v0.1. So i made my first meteor package, learned a lot on the way and last week it finally hit 1.0 \o/. There has been some demand for stucture of the packages recently and one move will be to make an official semantic-ui package. Even though i am sad to see my first baby go, i feel quite confident that all will be fine. 

This Package here will eventually deprecate and `semantic:ui` will be the official one. Lot easier to remember, right ;D

While we work on the new packages integration and structure at [Semanti-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor), i'll of couse keep this package up to date to the most recent tagged semantic-ui version. I'll warn you guys in the logs as soon as its time to switch over ;)

I thank everyone for their support and trust and hope the transition will be smooth for everyone.

Cheers!

**Comment by splendido** [comment]
You did an awesome work with this package @nooitaf!
You'd deserve more than one mention for this, undoubtedly!

...but I think the time has come to switch to `semantic:ui-css` ;-)

@jlukic just finished a huge refactorung of the SUI's build process and we're now set up and running for automatic publishes of new releases for both the whole CSS pacakge and single components ones.

See [Semantic UI on Atmosphere](https://atmospherejs.com/semantic) and the latest stream of automatic publishings on [autopublish.meteor.com](http://autopublish.meteor.com/).

At the moment efforts are moving to the design of the main `semantic:ui` package which should come with LESS files also allowing for themig!
See [this issue](https://github.com/Semantic-Org/Semantic-UI-LESS/issues/1).


Thank you again for the great commitment you have put on this package!
I personally hope you'll take the lead on the new official packages :-)

**Comment by nooitaf** [comment]
@splendido @jlukic This is great news :) Nice work of you guys! 
Also thank you for the kind words! *blush*

I'll update to `1.10.2` asap (tomorrow) and put an update warning in the readme and server console.

Would appreciate if you would ping me when the `less` package is ready so i can blow the dust of the old package and apply the same update warning.

**Comment by jlukic** [comment]
I'm sorry I somehow missed this thread. 

@nooitaf If you have any requests or run into any issues with the new packages let me know. I can give you access to the repos as well

**Comment by nooitaf** [comment]
Just a finishing link to the new Repository: https://github.com/Semantic-Org/Semantic-UI-Meteor/
