### ISSUE TITLE
Can't access Accordion

### ISSUE THREAD

**Issue by BillyParadise** [nooitaf/meteor-semantic-ui#35]
Hi, I'm attempting to rebuild the very useful accounts-entry package for Semantic UI.  One of the eye-candy features they use is to hide the username/password fields in an accordion when there are social logins available.

I'm trying to rewrite this for Semantic, but I can't get the accordion working.  In my code I have
```
Template.entrySignUp.rendered = function() {
  $('.ui.accordion').accordion()
 };
```

but no luck.

Any hints gratefully accepted!

Project URL is https://github.com/Miracula/accounts-entry-semantic-ui and will be contributed back once complete.

**Comment by nooitaf** [comment]
http://docs.meteor.com/#/full/template_rendered
"In the body of the callback, __this__ is a template instance object that is unique to this occurrence of the template and persists across re-renderings. "

So it should be..
````javascript
this.$('.ui.accordion').accordion()
````


Just tested this with 1.5.2.. 
````html
<head>
  <title>semantic-accordion-test</title>
</head>

<body>
  {{> home}}
</body>

<template name="home">
 <div class="ui accordion" >
	  <div class="title" id="signUpAccordion">
	    <div> t9n "signUpWithYourEmailAddress" </div>
	  </div>
	  <div class="content">
	      <h1>The Accordion Works!</h1>
	      <p>Move the passwordLoginService in here</p>
	  </div>
	</div>   
</template>
````
````javascript
if (Meteor.isClient) {
  // client/test.js
  Template.home.rendered = function(){
    this.$('.ui.accordion').accordion();
  }
}
````

**Comment by BillyParadise** [comment]
Many thanks - I'll get this Javascript stuff some day. Working as expected.

**Comment by nooitaf** [comment]
Great :)
In this case `this` is special with Meteor, because it should fire without `this` but the template wont be rendered yet. But you can be sure you are only acting only within the `home` template and not your whole page.
Within `rendered` the template is `this`. With `events` you get `(events,template)` delivered and `this` will be the current item/object.
