### ISSUE TITLE
event.preventDefault(); not firing from a form inside a modal and ui sticky issue

### ISSUE THREAD

**Issue by richardKafati** [nooitaf/meteor-semantic-ui#37]
I'm having a little trouble with event.preventDefault(); not firing from a form inside a modal and an issue with a "ui sticky" not functioning. The issue description is the in readme of this repo: https://github.com/richardKafati/MyFoodCurrent

repo is deplyed at http://myfood.meteor.com/

Feel free send a pull request.

**Comment by nooitaf** [comment]
I had a quick look, there is no conclusion, but a few points that might help.

When using events, you get the event and template delivered in the function
````javascript
````

**Comment by nooitaf** [comment]
damn command-return comment :(

**Comment by richardKafati** [comment]
it's ok. Take your time. :)

I'm going to sleep now. Thank you very much nooitaf.

**Comment by nooitaf** [comment]
I had a quick look, there is no conclusion, but a few points that might help.

I got an error in the browser saying "sticky too big", you have to give you right side container a min-size.

When using events, you get the event and template delivered in the function
````javascript
  'click .some' : function (e,t) {  // event, template
    e.preventDefault();
  }
````

Maybe try to use a template for the modal itself.
````html
<template name="food">
  <div class="four wide column">
   ...
  </div>

  {{> foodModal}}
  
</template>

<template name="foodModal">
  <div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
      {{food}}, {{foodCategory}}
    </div>
    <div class="content">
      <div class="image">
        <img src="{{imageUrl}}">
      </div>
      <div class="description">
        <input type="text" class="quantity" placeholder="{{quantity}}">
        <input type="text" class="quantityDescriptor" placeholder="{{quantityDescriptor}}">
      </div>
    </div>
    <div class="actions">
      <div class="ui button cancel">Cancel</div>
      <div class="ui button ok">OK</div>
    </div>
  </div>
</template>
````

Also maybe make use of the modal buttons i used above, that whay when you init the modal you can listen to the answer
````javascript
Template.food.events({
  "click .openModal": function (e,t) {
    foodNameWithoutSpaces = this.food.replace(/\s+/g, '');
    t.$('.modal')
      .modal({
        onDeny    : function(){
          console.log('canceled');
          return false;
        },
        onApprove : function() {
          console.log('pressed ok');
        }
      })
      .modal('show');
  },
});
````

You might even try to use just one Modal for all the fuits, as its the same every time. It might the also be simpler to select the values. remember that you have the _id at hand while initializing the modal and its `onApprove` function.

Its also easier to send a pull request if you push you project from the install path. Its missing the .meteor folder `packages` and such.

Hope that helps.
