### ISSUE TITLE
Modal does not work properly on Chrome (Meteor only)

### ISSUE THREAD

**Issue by tomitrescak** [nooitaf/meteor-semantic-ui#39]
I have encountered a strange behaviour, where modal is not rendering properly on Chrome, but only if it is done in a Meteor application. I have uploaded the test case here: https://dl.dropboxusercontent.com/u/3418607/modalTest.zip

It is a micro application which loads a modal on initial view.
When you run it as a meteor application modal will not be entered on screen and you will not be able to scroll (make your window smaller so that all content won't fit).

The moment you resize your window while modal is displayed the modal will jump into correct location and you are able to scroll.

I have also added to 'private/pureHtml.html' a html version of the same page, which behaves correctly. I have tried to narrow it down but with no success, all other browsers seem to be fine.

[EDIT] Neither safari works. Looks like only Firefox is working fine.

**Comment by nooitaf** [comment]
closing this, hope you found a solution

**Comment by tomitrescak** [comment]
Yes, I had to call refresh after all images were loaded.

**Comment by nooitaf** [comment]
Ah, makes sense. Thanks :)
