### ISSUE TITLE
Modal multiple binding in angularjs

### ISSUE THREAD

**Issue by olaray** [nooitaf/meteor-semantic-ui#40]
It appears $(".ui.modal").modal("show") binds twice in angularjs.

I observed that, when i call the modal("show") and then after performing all operations required, i navigate to another route (ngRoute) on coming back to the current route, when the event is triggered to show modal, the modal screen that is presented comes twice.

My code that triggers the modal is 

```js
$scope.doubleClick = function () {
            $('.ui.editCategory.modal').modal({
                closable: false,
                blurring: true,
                onDeny: function ()
                {
                },
                onApprove: function ()
                {
                }
            }).modal('show');
        };
```

How can i prevent this from happening

**Comment by xavi7th** [comment]
I have this same problem. Any solutions yet?

**Comment by nooitaf** [comment]
Sorry, i don't know. Not very familiar with angular.
This is also a Meteor package and deprecated for 3 years. 
You can find the current Meteor package here: https://github.com/Semantic-Org/Semantic-UI-Meteor
There is also an Angular semantic project here: https://github.com/Semantic-Org/Semantic-UI-Angular
