### ISSUE TITLE
Semantic-ui Search

### ISSUE THREAD

**Issue by diuzzoli** [nooitaf/meteor-semantic-ui#41]
There is a possibility of using "semantic-ui search" directly with "Meteor Collection" without invoking an API?

Something like...

```js
$('.ui.search')
  .search({
    collection: MyCollection.find({}),
    fields: {
      results : 'MyItem',
      title   : 'MyTitleArticle',
      url     : 'html_url'
    }
  })
;
```

Regards

**Comment by nooitaf** [comment]
Sorry, long time no reply. But i would guess thats not the case. It would be a nice syntax though.
Current project can be found here. https://github.com/Semantic-Org/Semantic-UI-Meteor 
This repository is deprecated and was more or less a temporary solution.
